# Generated by Django 5.2.7 on 2026-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_to_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='posted_to_youtube',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
