# Generated by Django 5.2.7 on 2026-06-21 02:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_posted_to_instagram_post_posted_to_youtube_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together={('user', 'platform')},
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
