"""
Django settings for growUp project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-rr8awn*9-lh9p6n7g(errkbipapj1qlqzqti_d97)rk8)t07zk'

DEBUG = True
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "arrythmical-meridith-unvenially.ngrok-free.dev"
]
# ----------------------------------------------------------
# INSTALLED APPS
# ----------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Required for allauth
    'django.contrib.sites',

    # Django allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.instagram',
    #'allauth.socialaccount.providers.youtube',
    'allauth.socialaccount.providers.facebook',


    # Your apps
    'core.apps.CoreConfig',
    'tailwind',
    'curvy',
    'django_browser_reload',
]

SITE_ID = 1
TAILWIND_APP_NAME = 'curvy'

# ----------------------------------------------------------
# AUTHENTICATION BACKENDS
# ----------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ----------------------------------------------------------
# LOGIN / LOGOUT SETTINGS
# ----------------------------------------------------------
LOGIN_URL = '/account/login/'
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# ----------------------------------------------------------
# DJANGO-ALLAUTH ACCOUNT SETTINGS
# ----------------------------------------------------------
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'none'   # or 'optional'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True      # ✅ auto-create user (important)
SOCIALACCOUNT_LOGIN_ON_GET = True


# ----------------------------------------------------------
# Instagram OAuth Settings
# ----------------------------------------------------------
INSTAGRAM_CLIENT_ID = "4099924166924965"
INSTAGRAM_CLIENT_SECRET = "758405ee85889118b25bb756bbc3fd49"
INSTAGRAM_REDIRECT_URI = "https://arrythmical-meridith-unvenially.ngrok-free.dev/auth/instagram/callback/"
INSTAGRAM_AUTH_URL = "https://api.instagram.com/oauth/authorize"
INSTAGRAM_TOKEN_URL = "https://api.instagram.com/oauth/access_token"
INSTAGRAM_API_URL = "https://graph.instagram.com"
# ----------------------------------------------------------
# SOCIAL ACCOUNT PROVIDERS (Google)
# ----------------------------------------------------------
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '792664826369-mu65ssejfl51hn72r6frefh01aummvu1.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'redirect_uri' : 'https://arrythmical-meridith-unvenially.ngrok-free.dev/account/google/login/callback/'
    }
}

# ----------------------------------------------------------
# MIDDLEWARE
# ----------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Allauth
    'allauth.account.middleware.AccountMiddleware',

    # Optional for dev reload
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

# ----------------------------------------------------------
# TEMPLATES
# ----------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # ✅ required by allauth
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ROOT_URLCONF = 'growUp.urls'
WSGI_APPLICATION = 'growUp.wsgi.application'

# ----------------------------------------------------------
# DATABASE
# ----------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ----------------------------------------------------------
# PASSWORD VALIDATORS
# ----------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ----------------------------------------------------------
# INTERNATIONALIZATION
# ----------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ----------------------------------------------------------
# STATIC FILES
# ----------------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CSRF_TRUSTED_ORIGINS = [
    "https://arrythmical-meridith-unvenially.ngrok-free.dev"
]